version: '3.3'
volumes:
  mongodb-volume:
    driver: 'local'
  elasticsearch-volume:
    driver: 'local'
services:
  mongodb:
    image: mongo:4.2.14
    volumes:
      - mongodb-volume:/data/db
    ports:
      - 27017:27017
  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - '4566:4566'
  #   environment:
  #     - SERVICES=${SERVICES- }
  #     - DEBUG=${DEBUG- }
  #     - DATA_DIR=${DATA_DIR- }
  #     - PORT_WEB_UI=${PORT_WEB_UI- }
  #     - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - LAMBDA_DOCKER_NETWORK=host
  #     - LAMBDA_EXECUTOR=docker-reuse
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'
