version: '3.3'
volumes:
  mongodb-volume:
    driver: 'local'
  localstack-volumes:
    driver: 'local'
services:
  mongodb:
    image: mongo:4.2.14
    volumes:
      - mongodb-volume:/data/db
    ports:
      - 27017:27017
  localstack:
    image: localstack/localstack:0.14.4
    ports:
      - 4566:4566
      - 8000:8080
    volumes:
      - type: bind
        source: ./localstack
        target: /tmp/localstack
      - type: bind
        source: ./.env.sample
        target: /opt/code/.env.sample
      # 初回起動スクリプト
      # - docker/localstack
      - ./docker/localstack:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
      # データのマウント
      - localstack-volumes:/tmp/localstack
    environment:
      - SERVICES=s3
      # s3のpresignedUrlを利用するためにはtestにしなければいけない
      # https://docs.localstack.cloud/integrations/aws-cli/#setting-up-local-region-and-credentials-to-run-localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1
